return {
  {
    "folke/which-key.nvim",
    keys = {
      {
        "<leader>hv?",
        function()
          require("which-key").show({ keys = "<leader>hv" })
        end,
        desc = "Vim Help Keymaps",
      },
      { "<leader>hvk", "<cmd>help quickref<cr>", desc = "Vim Quick Reference" },
      { "<leader>hvi", "<cmd>help index<cr>", desc = "Vim Help Index" },
      { "<leader>hvm", "<cmd>help motion.txt<cr>", desc = "Motions" },
      { "<leader>hvo", "<cmd>help operator<cr>", desc = "Operators" },
      { "<leader>hvt", "<cmd>help text-objects<cr>", desc = "Text Objects" },
      { "<leader>hvr", "<cmd>help registers<cr>", desc = "Registers" },
      { "<leader>hva", "<cmd>help q<cr>", desc = "Macros" },
      { "<leader>hvw", "<cmd>help windows.txt<cr>", desc = "Windows" },
      { "<leader>hvb", "<cmd>help buffers<cr>", desc = "Buffers" },
      { "<leader>hvf", "<cmd>help fold-commands<cr>", desc = "Folds" },
      { "<leader>hvq", "<cmd>help quickfix<cr>", desc = "Quickfix" },
      { "<leader>hvs", "<cmd>help pattern<cr>", desc = "Search Patterns" },
      { "<leader>hvc", "<cmd>help cmdline-editing<cr>", desc = "Command-line Editing" },
      { "<leader>hvx", "<cmd>help :global<cr>", desc = "Global Command" },
      { "<leader>hv.", "<cmd>help repeat<cr>", desc = "Repeat / Dot Command" },
    },
    opts = function(_, opts)
      opts.spec = opts.spec or {}
      vim.list_extend(opts.spec, {
        { "<leader>h", group = "help" },
        { "<leader>hv", group = "vim cheatsheet" },
        { "<leader>hv?", desc = "Show Vim Cheatsheet" },
        { "<leader>hvk", desc = "Vim Quick Reference" },
        { "<leader>hvi", desc = "Vim Help Index" },
        { "<leader>hvm", desc = "Motions" },
        { "<leader>hvo", desc = "Operators" },
        { "<leader>hvt", desc = "Text Objects" },
        { "<leader>hvr", desc = "Registers" },
        { "<leader>hva", desc = "Macros" },
        { "<leader>hvw", desc = "Windows" },
        { "<leader>hvb", desc = "Buffers" },
        { "<leader>hvf", desc = "Folds" },
        { "<leader>hvq", desc = "Quickfix" },
        { "<leader>hvs", desc = "Search Patterns" },
        { "<leader>hvc", desc = "Command-line Editing" },
        { "<leader>hvx", desc = "Global Command" },
        { "<leader>hv.", desc = "Repeat / Dot Command" },
        { "<leader>a", group = "ai" },
        { "<leader>ac", desc = "Toggle Codex" },
        { "<leader>a?", desc = "Show AI Keymaps" },
        { "<leader>d", group = "debug" },
        { "<leader>dg", group = "go debug" },
        { "<leader>db", desc = "Toggle Breakpoint" },
        { "<leader>dB", desc = "Conditional Breakpoint" },
        { "<leader>dC", desc = "Clear Breakpoints" },
        { "<leader>dc", desc = "Continue / Start" },
        { "<leader>de", desc = "Evaluate Expression" },
        { "<leader>dh", desc = "Hover Value" },
        { "<leader>di", desc = "Step Into" },
        { "<leader>do", desc = "Step Over" },
        { "<leader>dO", desc = "Step Out" },
        { "<leader>dp", desc = "Pause" },
        { "<leader>dr", desc = "Open REPL" },
        { "<leader>dR", desc = "Restart" },
        { "<leader>dl", desc = "Run Last Session" },
        { "<leader>dL", desc = "Log Point" },
        { "<leader>du", desc = "Toggle DAP UI" },
        { "<leader>dx", desc = "Terminate" },
        { "<leader>dt", desc = "Debug Go Test" },
        { "<leader>dT", desc = "Debug Last Go Test" },
        { "<leader>dm", desc = "Debug Go Main" },
        { "<leader>dga", desc = "Debug Go Package With Args" },
        { "<leader>dgf", desc = "Debug Go File" },
        { "<leader>dgm", desc = "Debug Go Package / Main" },
        { "<leader>dgt", desc = "Debug Go Test" },
        { "<leader>dgT", desc = "Debug Last Go Test" },
        { "<leader>d?", desc = "Show Debug Keymaps" },
        { "<leader>f", group = "find" },
        { "<leader>fb", desc = "Find Buffers" },
        { "<leader>fc", desc = "Find Commands" },
        { "<leader>ff", desc = "Find Files" },
        { "<leader>fg", desc = "Live Grep" },
        { "<leader>fk", desc = "Find Keymaps" },
        { "<leader>fr", desc = "Recent Files" },
        { "<leader>f?", desc = "Show Find Keymaps" },
        { "<leader>c", group = "code" },
        { "<leader>cg", group = "code goto" },
        { "<leader>ca", desc = "Code Action" },
        { "<leader>cA", desc = "Source Action" },
        { "<leader>cc", desc = "Run Codelens" },
        { "<leader>cC", desc = "Refresh Codelens" },
        { "<leader>cd", desc = "Line Diagnostics" },
        { "<leader>cf", desc = "Format" },
        { "<leader>cF", desc = "Format Injected Langs" },
        { "<leader>cl", desc = "LSP Info" },
        { "<leader>cr", desc = "Rename" },
        { "<leader>cR", desc = "Rename File" },
        { "<leader>cs", desc = "Symbols / Outline" },
        { "<leader>cS", desc = "LSP References / Definitions" },
        { "<leader>cgd", desc = "Definition" },
        { "<leader>cgD", desc = "Declaration" },
        { "<leader>cgi", desc = "Implementation" },
        { "<leader>cgr", desc = "References" },
        { "<leader>cgt", desc = "Type Definition" },
        { "<leader>c?", desc = "Show Code Keymaps" },
        { "<leader>t", group = "terminal" },
        { "<leader>tt", desc = "Toggle Terminal" },
        { "<leader>tg", desc = "Open LazyGit" },
        { "<leader>tc", desc = "Open Codex Terminal" },
        { "<leader>t?", desc = "Show Terminal Keymaps" },
        { "<leader>n", group = "notifications" },
        { "<leader>nd", desc = "Noice Dismiss" },
        { "<leader>nh", desc = "Noice History" },
        { "<leader>nl", desc = "Noice Last Message" },
        { "<leader>g", group = "git/github" },
        { "<leader>gh", group = "git hunks" },
        { "<leader>gb", desc = "Git Blame Line" },
        { "<leader>gd", desc = "Git Diff This" },
        { "<leader>gs", desc = "Git Status" },
        { "<leader>ghn", desc = "Next Hunk" },
        { "<leader>ghN", desc = "Previous Hunk" },
        { "<leader>ghb", desc = "Blame Line" },
        { "<leader>ghB", desc = "Blame Buffer" },
        { "<leader>ghd", desc = "Diff This" },
        { "<leader>ghD", desc = "Diff This ~" },
        { "<leader>ghp", desc = "Preview Hunk Inline" },
        { "<leader>ghr", desc = "Reset Hunk" },
        { "<leader>ghR", desc = "Reset Buffer" },
        { "<leader>ghs", desc = "Stage Hunk" },
        { "<leader>ghS", desc = "Stage Buffer" },
        { "<leader>ghu", desc = "Undo Stage Hunk" },
        { "<leader>ghv", desc = "Preview Hunk" },
        { "<leader>go", desc = "Octo Open" },
        { "<leader>gI", desc = "Octo Issue List" },
        { "<leader>gP", desc = "Octo PR List" },
        { "<leader>g?", desc = "Show Git/GitHub Keymaps" },
        { "<leader>cM", desc = "Open Mason" },
        { "<F5>", desc = "DAP Continue", mode = "n" },
        { "<F10>", desc = "DAP Step Over", mode = "n" },
        { "<F11>", desc = "DAP Step Into", mode = "n" },
        { "<F12>", desc = "DAP Step Out", mode = "n" },
      })
    end,
  },
}
